# Generated by Django 5.2.15 on 2026-06-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('constructor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('color_hex', models.CharField(default='#7f8c8d', max_length=7)),
                ('logo_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('given_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('headshot_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('current_constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.constructor')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('race_name', models.CharField(max_length=255)),
                ('circuit_name', models.CharField(max_length=255)),
                ('circuit_id', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='seasons.season')),
            ],
            options={
                'ordering': ['season', 'round'],
                'unique_together': {('season', 'round')},
            },
        ),
        migrations.CreateModel(
            name='QualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('q1', models.CharField(blank=True, max_length=50, null=True)),
                ('q2', models.CharField(blank=True, max_length=50, null=True)),
                ('q3', models.CharField(blank=True, max_length=50, null=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='seasons.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='seasons.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='seasons.race')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('race', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('position_text', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fastest_lap_time', models.CharField(blank=True, max_length=50, null=True)),
                ('fastest_lap_rank', models.IntegerField(blank=True, null=True)),
                ('pit_stops_count', models.IntegerField(blank=True, null=True)),
                ('tyres_used', models.CharField(blank=True, max_length=50, null=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='seasons.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='seasons.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='seasons.race')),
            ],
            options={
                'ordering': ['position', 'grid'],
                'unique_together': {('race', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('position', models.IntegerField()),
                ('wins', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='seasons.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='seasons.season')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('season', 'round', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('position', models.IntegerField()),
                ('wins', models.IntegerField(default=0)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='seasons.constructor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_standings', to='seasons.season')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('season', 'round', 'constructor')},
            },
        ),
    ]
